services:
  back-end:
    container_name: back-end
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command:
      sh -c "npm run start"

  front-end:
    build:
      context: ./front-end/basket-league
      dockerfile: Dockerfile
    container_name: front-end
    ports:
      - "80:81"